<?php

namespace srag\Plugins\VimpPageComponent\Config;

use ilVimpPageComponentPlugin;
use srag\ActiveRecordConfig\VimpPageComponent\ActiveRecordConfig;

/**
 * Class Config
 *
 * Generated by SrPluginGenerator v1.0.0
 *
 * @package srag\Plugins\VimpPageComponent\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class Config extends ActiveRecordConfig
{

    const TABLE_NAME = "copg_pgcp_vpco_config";
    const PLUGIN_CLASS_NAME = ilVimpPageComponentPlugin::class;
    const KEY_DEFAULT_HEIGHT = "default_height";
    const KEY_DEFAULT_WIDTH = "default_width";
    /**
     * @var array
     */
    protected static $fields
        = [
            self::KEY_DEFAULT_HEIGHT => self::TYPE_INTEGER,
            self::KEY_DEFAULT_WIDTH => self::TYPE_INTEGER
        ];
}
