<?php

namespace srag\Plugins\VimpPageComponent\Config;

use ilNumberInputGUI;
use ilVimpPageComponentConfigGUI;
use ilVimpPageComponentPlugin;
use ilTextInputGUI;
use srag\CustomInputGUIs\VimpPageComponent\PropertyFormGUI\ConfigPropertyFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by SrPluginGenerator v1.0.0
 *
 * @package srag\Plugins\VimpPageComponent\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ConfigFormGUI extends ConfigPropertyFormGUI
{

    const PLUGIN_CLASS_NAME = ilVimpPageComponentPlugin::class;
    const CONFIG_CLASS_NAME = Config::class;
    const LANG_MODULE = ilVimpPageComponentConfigGUI::LANG_MODULE;


    /**
     * ConfigFormGUI constructor
     *
     * @param ilVimpPageComponentConfigGUI $parent
     */
    public function __construct(ilVimpPageComponentConfigGUI $parent)
    {
        parent::__construct($parent);
    }


    /**
     * @inheritdoc
     */
    protected function initCommands()/*: void*/
    {
        $this->addCommandButton(ilVimpPageComponentConfigGUI::CMD_UPDATE_CONFIGURE, $this->txt("save"));
    }


    /**
     * @inheritdoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            Config::KEY_DEFAULT_HEIGHT => [
                self::PROPERTY_CLASS    => ilNumberInputGUI::class,
                self::PROPERTY_REQUIRED => false
            ],
            Config::KEY_DEFAULT_WIDTH => [
                self::PROPERTY_CLASS    => ilNumberInputGUI::class,
                self::PROPERTY_REQUIRED => false
            ]
        ];
    }


    /**
     * @inheritDoc
     */
    protected function initId()/*: void*/
    {

    }


    /**
     * @inheritDoc
     */
    protected function initTitle()/*: void*/
    {
        $this->setTitle($this->txt("configuration"));
    }
}
