<#1>
<?php
/**
 * Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE
 *
 * Generated by SrPluginGenerator v1.0.0
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
\srag\Plugins\VimpPageComponent\Config\Config::updateDB();
?>
